"""Train the production behaviour classifier.

Reads ``ai/data/synthetic.csv`` (generated by ``generate_dataset.py``),
trains a HistGradientBoostingClassifier, evaluates on a held-out test set,
and writes the artefact + a metrics report.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / "data"
MODELS = HERE.parent / "models"
REPORTS = HERE.parent / "reports"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=Path, default=DATA / "synthetic.csv")
    parser.add_argument("--out",  type=Path, default=MODELS / "behaviour.pkl")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    df = pd.read_csv(args.data)
    y = df.pop("label").values
    X = df.values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=args.seed, stratify=y)
    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.15, random_state=args.seed, stratify=y_train)

    model = HistGradientBoostingClassifier(
        max_iter=400,
        learning_rate=0.06,
        max_depth=8,
        random_state=args.seed,
    )
    model.fit(X_train, y_train)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, args.out)
    print(f"wrote model artefact to {args.out}")

    REPORTS.mkdir(parents=True, exist_ok=True)
    val_pred = model.predict(X_val)
    test_pred = model.predict(X_test)
    report = {
        "val_macro_f1": float(f1_score(y_val, val_pred, average="macro")),
        "test_macro_f1": float(f1_score(y_test, test_pred, average="macro")),
        "test_classification_report": classification_report(y_test, test_pred, output_dict=True),
        "test_confusion_matrix": confusion_matrix(y_test, test_pred).tolist(),
        "classes": sorted(set(y.tolist())),
        "n_train": len(X_train),
        "n_val": len(X_val),
        "n_test": len(X_test),
    }
    (REPORTS / "metrics.json").write_text(json.dumps(report, indent=2))
    print(f"val   macro-F1 = {report['val_macro_f1']:.3f}")
    print(f"test  macro-F1 = {report['test_macro_f1']:.3f}")


if __name__ == "__main__":
    main()
